package com.team2383.robot.autos.auto_chooser;

public class AutoQuestionResponses {
    public static enum QuestionResponses {
        CONE1, CUBE1, CONE2, CONE3, CUBE2, CONE4, CONE5, CUBE3, CONE6, STOP, ENGAGECOMMUNITY, ENGAGEOUTSIDE, HIGH, MEDIUM, HYBRID, MOBILITYCLEAN, MOBILITYDIRTY, MOBILITYCHARGE, FEEDCONECLEAN1, FEEDCUBECLEAN1, FEEDCONECLEAN2, FEEDCUBECLEAN2, FEEDCONEDIRTY1, FEEDCUBEDIRTY1, FEEDCONEDIRTY2, FEEDCUBEDIRTY2, FEEDCONECHARGE1, FEEDCUBECHARGE1, FEEDCONECHARGE2, FEEDCUBECHARGE2, NA
    }

}
