package com.team2383.robot.autos.auto_chooser;

public class AutoQuestionResponses {
    public static enum QuestionResponses {
        CONE1, CUBE1, CONE2, CONE3, CUBE2, CONE4, CONE5, CUBE3, CONE6, STOP, ENGAGECOMMUNITY, ENGAGEOUTSIDE, HIGH, MEDIUM, HYBRID, MOBILITYCLEAN, MOBILITYDIRTY, MOBILITYCHARGE, FEEDCONECLEAN, FEEDCONEDIRTY, FEEDCUBECLEAN, FEEDCUBEDIRTY, FEEDCONECHARGE, FEEDCUBECHARGE, NA
    }

}
